version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: inventory-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: inventory_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - inventory-network

  # Backend API Server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: inventory-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 8000
      DATABASE_URL: mongodb://admin:password123@mongodb:27017/inventory_db?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_for_development
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - inventory-network

  # Frontend React App
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: inventory-frontend
    restart: unless-stopped
    environment:
      VITE_BASE_URL: http://localhost:8000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - inventory-network

volumes:
  mongodb_data:

networks:
  inventory-network:
    driver: bridge
