version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: inventory-mongodb-prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-securepassword123}
      MONGO_INITDB_DATABASE: inventory_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - inventory-network

  # Backend API Server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: inventory-backend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8000
      DATABASE_URL: mongodb://admin:${MONGO_PASSWORD:-securepassword123}@mongodb:27017/inventory_db?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your_super_secret_jwt_key_change_this_in_production}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - inventory-network

  # Frontend React App
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: inventory-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - inventory-network

volumes:
  mongodb_data:

networks:
  inventory-network:
    driver: bridge
